### ISSUE TITLE
[Help] Server only connects with no security , fails to connect with SignAndEncrypt with username/password. 

### ISSUE THREAD

**Issue by jigar88** [locka99/opcua#129]
I am using server.conf file from the demo server for my server side application. I can connect with OPC server when I choose security None. If I choose other endpoint with security policy and security mode and apply the username and password from the server config server is not getting connected. Is secure mode supporting server ? 
![image](https://user-images.githubusercontent.com/75369224/127709727-4221cc1a-da52-482f-8d2d-50b45d9a44ef.png)

**Comment by locka99** [comment]
Yes it works. Make sure first your client's certificate is moved from the server's rejected/ to trusted/ folder otherwise the server will not accept the connection. If this doesn't work, check that your server cert matches where it is running, in case the client side is rejecting the server - some clients may also require you move the server's cert to a trusted/ folder.

I also have an integration test suite under integration/ that runs through all security profiles with anonymous, user-pass and x509 certificates and I ran it just 2 days ago and every test passed. This was after the recent update to tokio 1.8.x
